### ISSUE TITLE
Problem with Scrolling

### ISSUE THREAD

**Issue by srueegger** [Lovor01/makeiteasy-popup#1]
Thanks for the cool plugin.

I have a scrolling problem. I have customized the modal window via CSS so that the content can be scrolled.

```css
.wp-block-makeiteasy-popup {
  z-index: 950;
  height: 100% !important;
  .makeiteasy-popup-content-wrapper {
    height: 100%;
  }
  div[role="dialog"] {
    height: 100%;
    overflow-y: scroll;
    max-height: 60vh;
    border-radius: 2px;
  }
  .makeiteasy-popup-close svg {
    width: 40px;
    height: 40px;
    fill: var(--wp--preset--color--contrast) !important;
  }
}
```

Now I have the problem that when a modal opens, the content scrolls down as soon as it opens.

I tried to scroll up the content again using JavaScript with the "makeiteasy/openModal".

But the event does not seem to work. In any case, my "console.log" here is not output.

```js
document.addEventListener('DOMContentLoaded', function() {
  document.addEventListener( 'makeiteasy/openModal', function( event ) {
    console.log( 'Modal is open' );
  } );
});

```

Am I missing something here? Or do you have an idea?
